/* SPDX-FileCopyrightText: 2023-2024 AIM GmbH <info@aim-online.com> */
/* SPDX-License-Identifier: MIT OR GPL-2.0-or-later */

/*! \file AiHwArtixUS.h
    Declare Artix UltraScale+ specific functions in this file 
*/

#ifndef __AIHWARTIUS_H__
#define __AIHWARTIUS_H__

#include "Ai_cdef.h"

/* TCP communication area (Start at Address 0) */
/* All values as register DWORD index          */
#define ARTIXUS_REG_TCP_CONTROL          0x0000 /* 0x0000 */
#define ARTIXUS_REG_TCP_INPUT_0          0x0001 /* 0x0004 */
#define ARTIXUS_REG_TCP_INPUT_1          0x0002 /* 0x0008 */
#define ARTIXUS_REG_TCP_INPUT_2          0x0003 /* 0x000C */
#define ARTIXUS_REG_TCP_INPUT_3          0x0004 /* 0x0010 */
#define ARTIXUS_REG_TCP_INPUT_4          0x0005 /* 0x0014 */

#define ARTIXUS_REG_TCP_STATUS           0x0008 /* 0x0020 */
#define ARTIXUS_REG_TCP_OUTPUT_0         0x0009 /* 0x0024 */
#define ARTIXUS_REG_TCP_OUTPUT_1         0x000A /* 0x0028 */
#define ARTIXUS_REG_TCP_OUTPUT_2         0x000B /* 0x002C */
#define ARTIXUS_REG_TCP_BOOT_STATUS      0x002F /* 0x00BC */

#define ARTIXUS_REG_TCP_BOOT_STATUS_READY    0x52454459U /*REDY*/

#define ARTIXUS_REG_TT_HIGH              0x0038 /* 0x00E0 */
#define ARTIXUS_REG_TT_LOW               0x0039 /* 0x00E4 */
#define ARTIXUS_REG_TT_STATUS            0x003A /* 0x00E8 */
#define ARTIXUS_REG_TT_EXTENSION         0x003B /* 0x00EC */

#define ARTIXUS_REG_TCP_SW_VERSION       0x0040 /* 0x0100 */
#define ARTIXUS_REG_TIME_SOURCE_CONTROL  0x0041 /* 0x0104 */

#define ARTIXUS_REG_NOVRAM_BASE_OFFSET   0x80 /* 0x0200 */
#define ARTIXUS_REG_NOVRAM_MAGIC         (ARTIXUS_REG_NOVRAM_BASE_OFFSET)
#define ARTIXUS_REG_NOVRAM_SERIAL        (ARTIXUS_REG_NOVRAM_BASE_OFFSET + 0x04/4)
#define ARTIXUS_REG_NOVRAM_BOARDCFG      (ARTIXUS_REG_NOVRAM_BASE_OFFSET + 0x08/4)
#define ARTIXUS_REG_NOVRAM_HWVARIANT     (ARTIXUS_REG_NOVRAM_BASE_OFFSET + 0x0C/4)
#define ARTIXUS_REG_NOVRAM_BOARDTYPE     (ARTIXUS_REG_NOVRAM_BASE_OFFSET + 0x10/4)
#define ARTIXUS_REG_NOVRAM_FRONTEND_CAP  (ARTIXUS_REG_NOVRAM_BASE_OFFSET + 0x14/4)
#define ARTIXUS_REG_NOVRAM_FRONTEND_CAP2 (ARTIXUS_REG_NOVRAM_BASE_OFFSET + 0x34/4)
#define ARTIXUS_REG_NOVRAM_BOARDAPP_TYP  (ARTIXUS_REG_NOVRAM_BASE_OFFSET + 0x18/4)
#define ARTIXUS_REG_NOVRAM_BOARDAPP_TYP2 (ARTIXUS_REG_NOVRAM_BASE_OFFSET + 0x3C/4)
#define ARTIXUS_REG_NOVRAM_PARTNO        (ARTIXUS_REG_NOVRAM_BASE_OFFSET + 0x1C/4)
#define ARTIXUS_REG_NOVRAM_PARTNO_EXT    (ARTIXUS_REG_NOVRAM_BASE_OFFSET + 0x20/4)
#define ARTIXUS_REG_NOVRAM_FIRSTDATE     (ARTIXUS_REG_NOVRAM_BASE_OFFSET + 0x28/4)
#define ARTIXUS_REG_NOVRAM_ACTDATE       (ARTIXUS_REG_NOVRAM_BASE_OFFSET + 0x2C/4)
#define ARTIXUS_REG_NOVRAM_PHY1RAM_SIZE  (ARTIXUS_REG_NOVRAM_BASE_OFFSET + 0x40/4)
#define ARTIXUS_REG_NOVRAM_PHY2RAM_SIZE  (ARTIXUS_REG_NOVRAM_BASE_OFFSET + 0x44/4)
#define ARTIXUS_REG_NOVRAM_GRAM_SIZE     (ARTIXUS_REG_NOVRAM_BASE_OFFSET + 0x50/4)
#define ARTIXUS_REG_NOVRAM_MLCAEX        (ARTIXUS_REG_NOVRAM_BASE_OFFSET + 0x70/4)
#define ARTIXUS_REG_NOVRAM_BIP1EX        (ARTIXUS_REG_NOVRAM_BASE_OFFSET + 0x80/4)
#define ARTIXUS_REG_NOVRAM_BIP2EX        (ARTIXUS_REG_NOVRAM_BASE_OFFSET + 0x84/4)
#define ARTIXUS_REG_NOVRAM_IRIG_OFFSET   (ARTIXUS_REG_NOVRAM_BASE_OFFSET + 0xF4/4)
#define ARTIXUS_REG_NOVRAM_CHECK_SUM     (ARTIXUS_REG_NOVRAM_BASE_OFFSET + 0xFC/4)






/* Global Register Area (Start at Address 0x400) */
/* All values as register DWORD index          */
#define ARTIXUS_REG_GPIO_OUTPUT          0x102 /* 0x408 */ /* Read/Write */
#define ARTIXUS_REG_GPIO_INPUT           0x103 /* 0x40C */ /* Read       */
#define ARTIXUS_REG_PL_VERSION           0x104 /* 0x410 */ /* Read       */
#define ARTIXUS_REG_GPIO_CONFIG          0x107 /* 0x41C */ /* Read/Write */


/* Interrupt Register Area */
#define ARTIXUS_REG_IRQ_HOST_EVENT       0x112 /* 0x448 */
#define ARTIXUS_REG_IRQ_HOST_MASK        0x113 /* 0x44C */

#define ARTIXUS_IRQ_BIU_1               (1<<8)
#define ARTIXUS_IRQ_BIU_2               (1<<9)
#define ARTIXUS_IRQ_BIU_3               (1<<10)
#define ARTIXUS_IRQ_BIU_4               (1<<11)
#define ARTIXUS_IRQ_DMA_C2H_CH2         (1<<23) /* Reserved */
#define ARTIXUS_IRQ_DMA_C2H_CH1         (1<<24)


#define ARTIXUS_IRQ_ALL                 (ARTIXUS_IRQ_BIU_1 | ARTIXUS_IRQ_BIU_2 | ARTIXUS_IRQ_BIU_3 | ARTIXUS_IRQ_BIU_4 | ARTIXUS_IRQ_DMA_C2H_CH1)

/* External Irig Register Area */
#define ARTIXUS_REG_EXTERNAL_IRIG_RESET       0x131 /* 0x4C4 */
#define ARTIXUS_REG_EXTERNAL_IRIG_PULSE       0x132 /* 0x4C8 */

/* IRIG */
#define ARTIXUS_REG_TIME_SOURCE_CONTROL_BIT_EXTERN     (1<<8)
#define ARTIXUS_REG_TIME_SOURCE_CONTROL_BIT_OUT_SIGNAL (1<<1)
#define ARTIXUS_REG_TIME_SOURCE_CONTROL_BIT_INSTANT    (1<<0)

/* Trigger Loop */
#define ARTIXUS_REG_TRIGGER_DIGITAL_LOOP 0x133 /* 0x4CC */

/* DMA */
#define ARTIXUS_DMA_CONFIG                    0x200 /* 0x800 */
#define ARTIXUS_DMA_C2H_CH1_SGL_START_ADDRESS 0x204 /* 0x810 */
#define ARTIXUS_DMA_C2H_CH1_SGL_FIFO_STATUS   0x205 /* 0x814 */
#define ARTIXUS_DMA_C2H_CH2_SGL_START_ADDRESS 0x208 /* 0x820 */
#define ARTIXUS_DMA_C2H_CH2_SGL_FIFO_STATUS   0x209 /* 0x824 */

#define ARTIXUS_DMA_CONFIG_DIRECTION_GLOBAL 0
#define ARTIXUS_DMA_CONFIG_DIRECTION_MS     1
#define ARTIXUS_DMA_SGL_FIFO_MAX_MASK       0xF     /* Bit 0..3 */
#define ARTIXUS_DMA_SGL_FIFO_MAX_ENTRIES    8
#define ARTIXUS_DMA_CONFIG_C2H_MASK         0x7     /* Bit 0..2 */
#define ARTIXUS_DMA_CONFIG_RESET            0x80    /* Bit 7 (self clearing) */



/* Artix7 Monitor/TCP commands and defines */
#define ARTIXUS_MON_CMD_MYMON_VER           0x01
#define ARTIXUS_MON_CMD_NOVRAM_FLUSH        0x31
#define ARTIXUS_MON_CMD_IRIG_SET            0x40
#define ARTIXUS_MON_CMD_IRIG_SET_DECODER    0x49
#define ARTIXUS_MON_CMD_FLASH_BLOCK_WRITE   0x50
#define ARTIXUS_MON_CMD_FLASH_SECTOR_ERASE  0x51
#define ARTIXUS_MON_CMD_FLASH_SECTOR_VERIFY 0x52


#define ARTIXUS_MON_OK                    0x0000
#define ARTIXUS_MON_PASS                  0x01

#define ARTIXUS_MON_ERR_MEM_ACCESS_FAILED 0x0005
#define ARTIXUS_MON_ERR_TIMEOUT           0x0006
#define ARTIXUS_MON_ERR_STATUS            0x0007
#define ARTIXUS_MON_ERR_RANGE_CHECK       0x0008
#define ARTIXUS_MON_ERR_BUSY              0x0009

#define ARTIXUS_MON_STATUS_FREE           0x00400000
#define ARTIXUS_MON_STATUS_WORKING        0x00800000
#define ARTIXUS_MON_STATUS_MASK           0x00C00000
#define ARTIXUS_MON_STATUS_CMD            0xFF000000


#endif /* __AIHWARTIX_H__ */


